#!/usr/bin/env python
#coding=utf-8

from tornado.web import RequestHandler
import users_api
import media_api
import locations_api

class LocationsHandler(RequestHandler):
	"""docstring for user"""
	def get(self):
		locations_id = self.request.arguments['locations_id']
		location = locations_api.get_locations(locations_id)

class SearchHandler(RequestHandler):
	"""docstring for user"""
	def get(self):
		latitude = self.request.arguments['latitude']
		longitude = self.request.arguments['longitude']
		min_id = self.request.arguments['min_id'] 
		max_id = self.request.arguments['max_id'] 
		count = self.request.arguments['count']

		locations = locations_api.get_locations_search(latitude, longitude, min_id, max_id, count)

class MediaHandler(RequestHandler):
	"""docstring for user"""
	def get(self):
		location_id = self.request.arguments['location_id']
		medias = locations_api.get_locations_media(location_id)
	